### ISSUE TITLE
Allow Advanced Avatar Settings to Override SDK Parameters

### ISSUE THREAD

**Issue by 200Tigersbloxed** [200Tigersbloxed/CVRParamLib#11]
Once an SDK has registered a parameter (either through an SDK or OSC), you cannot drive that parameter through the Advanced Avatar Settings, until the Parameter is deleted from cache.

**Comment by kafeijao** [comment]
Is there a reason to enforce the cached values into the game at all?

Asking because there are other ways to drive parameters, like using animator drivers, or triggers. How OSC worked in VRC is you set the value upon receiving a OSC message and that's it.

I have no data to support this since I didn't test, but I feel like keeping a cache updated by checking every frame will be less performant than just getting the value straight from the source when needed.

I'm sorry if I'm being too picky/annoying (feel free to tell me so). I just depend on OSC a lot, that's why I'm here x)

**Comment by 200Tigersbloxed** [comment]
> Is there a reason to enforce the cached values into the game at all?

It makes it easier to identify which of our parameters are parameters we are currently controller, if we ever do have the scenario when we need to know.

> Asking because there are other ways to drive parameters, like using animator drivers, or triggers. How OSC worked in VRC is you set the value upon receiving a OSC message and that's it.

Don't forget that because of the OSC Debug menu, they too also have to cache which parameters are OSC driven and not.

> keeping a cache updated by checking every frame will be less performant than just getting the value straight from the source when needed.

The source that we pull data from is that cache, a.k.a.

```cs
string parametername = "..."
float value = ParameterManager.Parameters[parametername]
```

Which is not going to tank your game's FPS. At most, it'll use a couple of KBs of memory.

> I'm sorry if I'm being too picky/annoying (feel free to tell me so).

Nah no worries, I strive to design the mod as performant as possible!

However, my current plan is this. There's a method in the ViewManager (the thingy that controls cohtml stuffz) where I can hook into one of the UI Bindings, called `CVRAppCallChangeAnimatorParam`. Upon this invocation, I can simply remove the cached parameter, which will give all control back to the user, until OSC or the SDK requests control of the parameter again.

**Comment by 200Tigersbloxed** [comment]
The change has been pushed to [c02fc30](https://github.com/200Tigersbloxed/CVRParamLib/commit/c02fc30fd7ae6e652afbe7417bb49e111f32cd91) and seems to function properly.
